app_admin_etl_execution:
    type: sylius.resource
    prefix: /admin
    resource: |
        alias: app.etl_execution
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        grid: app_admin_etl_execution
        permission: true
        vars:
            all:
                subheader: sylius.ui.etl_execution.grid.title
                header: sylius.ui.etl_execution.grid.title

app_admin_etl_execution_dashboard:
    path: admin/etl-executions/dashboard
    methods: [ GET ]
    defaults:
        _controller: 'Oliverde8\PhpEtlSyliusAdminBundle\Controller\DashboardController::indexAction'
        _sylius:
            section: admin
            permission: true

app_admin_etl_execution_edit:
    path: admin/etl-executions/edit/{id}
    methods: [ GET, POST ]
    defaults:
        _controller: 'Oliverde8\PhpEtlSyliusAdminBundle\Controller\EtlController::editAction'
        _sylius:
            section: admin
            permission: true
    
app_admin_etl_execution_execute:
    path: admin/etl-executions/execute/{id}
    methods: [ GET ]
    defaults:
        _controller: 'Oliverde8\PhpEtlSyliusAdminBundle\Controller\EtlController::ExecuteAction'
        _sylius:
            section: admin
            permission: true
            
app_admin_etl_execution_delete:
    path: admin/etl-executions/delete/{id}
    methods: [ DELETE ]
    defaults:
        _controller: 'Oliverde8\PhpEtlSyliusAdminBundle\Controller\EtlController::deleteAction'
        _sylius:
            section: admin
            permission: true
            
app_admin_etl_execution_download:
    path: admin/etl-executions/download/{id}/{filename}
    methods: [ GET ]
    defaults:
        _controller: 'Oliverde8\PhpEtlSyliusAdminBundle\Controller\EtlController::downloadAction'
        _sylius:
            section: admin
            permission: true
            
app_admin_etl_execution_show:
    path: admin/etl-executions/{id}
    methods: [ GET ]
    defaults:
        _controller: 'Oliverde8\PhpEtlSyliusAdminBundle\Controller\EtlController::showAction'
        _sylius:
            section: admin
            permission: true
    
