sylius_grid:
    templates:
        filter:
            etl_execution_name: "@SyliusUi/Grid/Filter/select.html.twig"
        action:
            executeEtl: "@Oliverde8PhpEtlSyliusAdmin/etl/grid/actions/execute_etl.html.twig"
            editEtl: "@Oliverde8PhpEtlSyliusAdmin/etl/grid/actions/update_etl.html.twig"
    grids: 
        oliverde8_admin_etl_execution:
            driver:
                name: doctrine/orm
                options:
                    class: Oliverde8\PhpEtlSyliusAdminBundle\Entity\Etl\EtlExecution
                    repository:
                        method: createAdminGridQueryBuilder
            fields:
                id:
                    type: string
                    label: "ID"
                name:
                    type: string
                    label: sylius.ui.etl_execution.grid.name
                createTime:
                    type: datetime
                    label: sylius.ui.etl_execution.grid.createTime
                startTime:
                    type: datetime
                    label: sylius.ui.etl_execution.grid.startTime
                endTime:
                    type: datetime
                    label: sylius.ui.etl_execution.grid.endTime
                status:
                    label: sylius.ui.etl_execution.grid.status
                    type: twig
                    options:
                        template: "@Oliverde8PhpEtlSyliusAdmin/etl/grid/fields/etl_status.html.twig"
            
            filters:
                name:
                    type: etl_execution_name
                    label: sylius.ui.etl_execution.grid.name
                status:
                    type: select
                    label: sylius.ui.etl_execution.grid.status
                    form_options:
                        choices:
                            "sylius.ui.etl_execution.statuses.success": "success"
                            "sylius.ui.etl_execution.statuses.running": "running"
                            "sylius.ui.etl_execution.statuses.failure": "failure"
                            "sylius.ui.etl_execution.statuses.waiting": "waiting"
                            "sylius.ui.etl_execution.statuses.queued": "queued"
                startTime:
                    type: date
                    label: sylius.ui.etl_execution.grid.startTime
                endTime:
                    type: date
                    label: sylius.ui.etl_execution.grid.endTime
                createTime:
                    type: date
                    label: sylius.ui.etl_execution.grid.createTime
            
            actions:
                main:
                    create:
                        type: create
                        options:
                            link:
                                route: oliverde8_admin_etl_execution_new
                item:
                    show:
                        type: show
                        enabled: true
                        label: ""
                    
                    delete:
                        type: delete
                        label: sylius.ui.etl_execution.grid.delete
                        enabled: true
                        options:
                            link:
                                route: oliverde8_admin_etl_execution_delete
                                parameters:
                                    id: resource.id
                                data:
                                    status: resource.status
