sylius_resource:
    resources:
        oliverde8.etl_execution:
            driver: doctrine/orm
            classes:
                model: Oliverde8\PhpEtlSyliusAdminBundle\Entity\Etl\EtlExecution
                form: Oliverde8\PhpEtlSyliusAdminBundle\Form\Type\Etl\EtlExecutionType
